<?php
$BOT_TOKEN='8390747300:AAF0V8Z_Ys3qTuWgKCQHLy4zoxvTxDhYKCg';
$SUPPORT_CHAT='-1002827751730';
$PUBLIC_CHANNEL_ID='@atb_club';
$TG_SECRET_TOKEN='ATB_SECRET_2025';
if(!defined('SUPPORT_CHAT')) define('SUPPORT_CHAT',$SUPPORT_CHAT);
if(!defined('PUBLIC_CHANNEL_ID')) define('PUBLIC_CHANNEL_ID',$PUBLIC_CHANNEL_ID);
if(!defined('TG_SECRET_TOKEN')) define('TG_SECRET_TOKEN',$TG_SECRET_TOKEN);
if(!defined('SAFE_MODE')) define('SAFE_MODE', true);
